### ISSUE TITLE
does not work when subpage contains the domain name

### ISSUE THREAD

**Issue by hefan** [somatonic/Multisite#2]
Hello,

Maybe just a minor flaw, but in a setup like this

```
home
  domain.de
    domain.de subpage
```

the call to http://domain.de/domain.de-subpage
gives a 404

this means that a name of any subpage can not contain the domain name.

best regards,
stefan

**Comment by somatonic** [comment]
I'm aware of issues with subpages having the domain name, and also with subdomains and domain. It's a issue of lazy coding with strpos. Will soon have a look when I get time.

**Comment by somatonic** [comment]
If you don't mind testing this  one out with the latest dev https://github.com/somatonic/Multisite/tree/dev version and report back? Thanks

**Comment by hefan** [comment]
thank you, looks promising.
But my dev environment setup works another way, seems to complicated to switch for now. i stick with the old version, works great. 
For the next pw-multisite project i will have another look..
