### ISSUE TITLE
view link in page edit screen does not link to correct url

### ISSUE THREAD

**Issue by hefan** [somatonic/Multisite#3]
the view link in the page edit screen does not link to the correct domain (though the view link in the page tree does).

**Comment by somatonic** [comment]
Thanks. I don't see that here, but that's possibly due to me having a newer version.

**Comment by somatonic** [comment]
If you get a chance to update and test to new dev branch https://github.com/somatonic/Multisite/tree/dev thanks!

**Comment by hefan** [comment]
thank you, looks promising.
But my dev environment setup works another way, seems to complicated to switch for now. i stick with the old version, works great. 
For the next pw-multisite project i will have another look..
