### ISSUE TITLE
Two issues

### ISSUE THREAD

**Issue by tomfrit** [somatonic/Multisite#5]
I'm getting a

Notice: Undefined index: it in /site/modules/Multisite/Multisite.module on line 68

 all the time. Also any request to a page of my subdomain homepage(ie subdomain.de/subpage) gets redirected to the homepage (subdomain.de) ... I can't reallly figure it out but I saw this fork is rather active so I figured I might as well ask :)
Thanks,
thomas

**Comment by somatonic** [comment]
This should be fixed in the latest commits in dev branch https://github.com/somatonic/Multisite/tree/dev
